# Generated by Django 4.2.4 on 2023-08-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.CharField(max_length=16)),
                ('productName', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
