# Generated by Django 4.2.4 on 2023-08-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(auto_created=True, max_length=16, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
